name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get Current Date and Time
        id: get_datetime
        run: echo "::set-output name=date_time::$(date +'%d.%m.%Y %H:%M')"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.get_datetime.outputs.date_time }}
          release_name: Release ${{ steps.get_datetime.outputs.date_time }} (${GITHUB_SHA:0:8})
          body: |
            ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: false
